GarageSale/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from .views import general_views

from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", general_views.home, name="home"),
    path("newhome", TemplateView.as_view(template_name='home.html'), name="NewHome"),
    path("getInvolved", RedirectView.as_view(url=reverse_lazy('Location:view'))),
#    path("getInvolved", include('Location.urls'), name="getInvolved"),
    path('about_us', TemplateView.as_view(template_name='aboutUs.html'), name='AboutUs'),
    path('contact', TemplateView.as_view(template_name='contact.html'), name='ContactUs'),
    path('privacy', TemplateView.as_view(template_name='privacy_policy.html'), name='Privacy'),
    path('blind_auction', TemplateView.as_view(template_name='blind_auction.html'), name='BlindAuction'),
    path('donate', TemplateView.as_view(template_name='donate.html'), name='Donate'),
    path('location/', include('Location.urls')),
    path('team_page/', include('team_pages.urls', 'TeamPages')),
    path('news/', include('News.urls')),
    path('user/', include('user_management.urls')),
#    path('billboard/', include('Billboard.urls')),
#    path('sale_location/', include('SaleLocation.urls')),

    # path('test/<int:case>/', views.testing, name='test'),
    path('sponsors/', include('Sponsors.urls')),
    path('CraftMarket/', include('CraftMarket.urls')),
    path('Account/', include('Accounts.urls')),

    path('mapping/', include('DjangoGoogleMap.urls')),
    path('summernote/', include('django_summernote.urls')),

    path("GoogleDrive/", include('GoogleDrive.urls', namespace='GoogleDrive') ),

]


if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

News/urls.py
#!/usr/bin/env python
# coding=utf-8
"""
    GarageSale.urls.py : 

Summary :
    
    
Use Case :
    
    
Testable Statements :
    ...0
"""
from .views import Article, news_page,news_letter_subscribe

from django.urls import path

app_name = "News"

urlpatterns = [
    path("", news_page, name="NewsPage"),
    path("article/<slug:slug>", Article.as_view(), name="article"),
    path("subscribe", news_letter_subscribe, name='subscribe'),
]

team_pages/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from GarageSale.views.template_views import TemplatesView
from . import views
from . import stats_view

app_name = 'TeamPages'
urlpatterns = [
    path('', views.TeamPage.as_view(), name='Root'),
    path('<int:event_id>/', views.TeamPage.as_view(), name='EventRoot'),
    path('<int:event_id>/stats/', stats_view.event_stats, name='EventStats'),

    # TODO Rework without Generic Views = more trouble than they are worth
    path('motd/create/', views.MotDCreate.as_view(), {'action': '_create'}, name='MotdCreate', ),
    path('motd/<int:motd_id>/edit/', views.MotDEdit.as_view(), name='MotdEdit'),
    path('motd/<int:motd_id>/view/', views.MotDView.as_view(), name='MotdView'),
    path('motd/<int:motd_id>/delete/', views.delete_motd, name='MotdDelete'),

    path('news/', views.NewsRoot.as_view(), name='News'),
    path('news/create/', views.NewsCreate.as_view(), name='CreateNews'),
    path('news/<int:news_id>/edit/', views.NewsEdit.as_view(), name='EditNews'),
    path('news/<int:news_id>/view/', views.NewsView.as_view(), name='ViewNews'),
    path('news/<int:news_id>/publish/', views.PublishNews, name='PublishNews'),
    path('news/<int:news_id>/delete/', views.NewsDelete.as_view(), name='DeleteNews'),

    path('event/', views.TeamPage.as_view(), name='Event'),
    path('event/<int:event_id>/', views.TeamPage.as_view(), name='EventDisplay'),

    path('event/create/', views.EventCreate.as_view(), name='EventCreate'),
    path('event/<int:event_id>/edit/', views.EventEdit.as_view(), name='EventEdit'),
    path('event/<int:event_id>/view/', views.EventView.as_view(), name='EventView'),
    path('event/<int:event_id>/use/', views.event_use, name='EventUse'),
    path('event/<int:event_id>/ad_board/',views.ad_board_csv, name='EventAdBoard'),

    path('sponsor/<int:event_id>/', views.SponsorsRoot.as_view(), name='Sponsor'),
    path('sponsor/<int:event_id>/create/', views.SponsorCreate.as_view(), name='SponsorCreate'),
    path('sponsor/<int:sponsor_id>/view/', views.SponsorView.as_view(), name='SponsorView'),
    path('sponsor/<int:sponsor_id>/edit/', views.SponsorEdit.as_view(), name='SponsorEdit'),
    path('sponsor/<int:sponsor_id>/confirm/', views.SponsorConfirm.as_view(), name='SponsorConfirm'),
    path('sponsor/<int:sponsor_id>/delete/', views.SponsorDelete.as_view(), name='SponsorConfirm'),
    path("GoogleDrive/", TemplateView.as_view(template_name='GoogleDrive.html'), name='GoogleDrive'),
]

News/models.py
import datetime

from django.db import models

from django.db.models import  Q, DEFERRED
from django_quill.fields import QuillField
from datetime import date
from django.utils.text import slugify

from GarageSale.management.commands.CheckGroups import default_permissions


class NewsPageOrder(models.Manager):
    """Manager that returns all news articles in published order"""

    def get_queryset(self):
        return (super().get_queryset().
                filter(publish_by__lte=date.today()).
                filter(Q(expire_by__gte=date.today()) | Q(expire_by__isnull=True)).
                filter(published=True).
                order_by('front_page', '-publish_by'))


class NewsQuerySet(models.query.QuerySet):
    def published_and_unpublished(self):
        return self.filter(Q(published=True) | Q(published=False))

    def unpublished_only(self):
        return self.filter(published=False)

    def published_only(self):
        return self.filter(published=True)

    def exclude_published(self):
        return self.exclude(published=True)

    def expired(self):
        return self.filter(Q(expire_by__gte=date.today()) & Q(expire_by__isnull=False))

    def past_publish_by(self):
        return self.filter(publish_by__lte=date.today())

    def sort_by_normal(self):
        return self.order_by('front_page', '-publish_by')


class Ticker(NewsPageOrder):
    """Manager for Ticker items only"""

    def get_queryset(self):
        return super().get_queryset().values('slug', 'headline')


class FrontPageOnly(NewsPageOrder):
    """Manager that gives the Front page only articles"""

    def get_queryset(self):
        return super().get_queryset().filter(front_page=True)


class Expired(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(expire_by__lt=date.today()).order_by('expire_by')


class UnPublished(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(published=False).order_by('publish_by')


# Create your models here.
class NewsArticle(models.Model):
    objects = models.Manager()
    FrontPageOrder = FrontPageOnly()
    news_page_order = NewsPageOrder()
    chainable = NewsQuerySet.as_manager()

    slug = models.SlugField()
    creation_date = models.DateTimeField(auto_now_add=True)
    publish_by = models.DateField(db_index=True, default=date.today)
    expire_by = models.DateField(db_index=True, null=True, blank=True)
    headline = models.CharField(max_length=256)
    front_page = models.BooleanField(default=False, db_index=True)
    content = QuillField(default='')
    synopsis = models.CharField(max_length=256, null=True, blank=True)
    published = models.BooleanField(default=False)

    class Meta:
        permissions = [ ("publish_news", "Can publish a news Article"),
        ]


    @property
    def is_live(self):
        """Is this item live (ie visible to user)
           i.e. The published flag is set and it is between the publish_by and expire_by dates
        """
        return (self.published and
                ((self.expire_by is not None and self.publish_by <= datetime.date.today() <= self.expire_by) or
                 (self.expire_by is None and self.publish_by <= datetime.date.today())))

    def save(self, force_insert=False, force_update=False,
             using=None,
             update_fields=None,
             ):

        self.slug = slugify(self.headline)
        if update_fields is not None and ('headline' not in update_fields or 'slug' not in update_fields):
            update_fields = {'headline', 'slug'}.union(update_fields)

        return super().save(force_insert=force_insert, force_update=force_update, using=using,
                            update_fields=update_fields)

    @property
    def can_be_published(self):
        """ return True if this article can be published
            ie currently un-published and not expired
        """
        return not self.published and (self.expire_by is None or self.expire_by > datetime.date.today())


class NewsLetterMailingList(models.Model):
    user_email = models.EmailField(unique=True)
    last_sent = models.DateField(null=True)

News/forms.py
#!/usr/bin/env python
# coding=utf-8

from django_quill.forms import QuillFormField
from django.forms import ModelForm
from .models import NewsArticle


class NewsArticle(ModelForm):
    class Meta:
        model = NewsArticle
        content = QuillFormField()
        fields = ['headline', 'content', 'publish_by', 'expire_by', 'front_page']

team_pages/forms.py
import datetime

from django import forms

from GarageSale.models import EventData, MOTD
from Sponsors.models import Sponsor
from News.models import NewsArticle


class EventForm(forms.ModelForm):
    class Meta:
        model = EventData
        fields = '__all__'


class SponsorForm(forms.ModelForm):
    class Meta:
        model = Sponsor
        exclude =['event']
        widgets = {'gift': forms.Textarea(attrs={'cols':50,'rows':2}),
                   'description': forms.Textarea(attrs={'cols':50,'rows':4}),
                }


class MotdForm(forms.ModelForm):
    class Meta:
        model = MOTD
        fields = '__all__'


class NewsForm(forms.ModelForm):
    class Meta:
        model = NewsArticle
        fields = '__all__'
        widgets = {'publish_by': forms.DateInput(attrs={'type': 'date'}),
                   'expire_by': forms.DateInput(attrs={'type': 'date'}),
                   'synopsis': forms.Textarea(attrs={'cols':45,'rows':4})}
        exclude = ['slug', 'published']

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data['front_page'] and not cleaned_data['synopsis']:
            self.add_error('synopsis', 'A synopsis must be provided for articles intended for the front-page')

News/views.py
from django.shortcuts import render

# Create your views here.

from django.views import View
from .forms import NewsArticle as NewsForm
from .models import NewsArticle as NewsModel, NewsLetterMailingList
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseServerError, HttpRequest


def publish_news(request, news_id):
    """Change the published status of the given article
       There are no safeguards on the view - they are done via the GUI
       Essentially :
            An article can be published if can_be_published is True
            An article can only be unpublished if it is already published
    """
    try:
        article = NewsModel.objects.get( id = news_id)
    except NewsModel.DoesNotExist:
        return HttpResponseServerError(f'News item does not exist {news_id}')

    article.published = not article.published
    article.save()
    return


def news_page(request):
    qs = NewsModel.news_page_order.all()
    return render(request, template_name='news_page.html', context={'articles': qs})


def news_letter_subscribe(request : HttpRequest):
    if request.method != "POST":
        return HttpResponseServerError("news_letter_subscribe : expecting a POST action")

    action = request.POST.get('action', None)
    user = request.user

    qs = NewsLetterMailingList.objects.filter(user_email=user.email)
    match action:
        case "Subscribe":
            if len(qs) == 0:
                inst = NewsLetterMailingList(user_email=user.email, last_sent=None)
                inst.save()
            return redirect("getInvolved")
        case "UnSubscribe":
            if len(qs) == 1:
                inst = qs[0]
                inst.delete()
            return redirect("getInvolved")
        case "_":
            return HttpResponseServerError(f'news_letter_subscribe : unexpected value {action} for action field')


class Article(View):
    form = NewsForm

    def get(self, request, slug=None, *args, **kwargs):
        if slug is not None:
            article = get_object_or_404( NewsModel, slug=slug)
            return render(request, template_name='news_article.html', context={'article': article})

        return HttpResponseServerError()

team_pages/templates/news/tp_create_news.html
{% extends "news/tp_manage_news_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block Title %}
        Brantham Garage Sale - Team Page: Create News Article
{% endblock %}

{% block details %}

<div class="detail bordered">
        <form method="post">
            {{form.media}}
            {%csrf_token%}
            <div class="table">
                <div class="table-row" >
                    <span class="table-cell label"><label for="id_headline">Headline</label></span>
                    <span class="data">{{form.headline}}</span>
                </div>
                <div class="table-row heading" >
                    <div class="table-cell label" ><label for="id_content">Content</label></div>
                    <div class="content data">
                            {{form.content}}
                   </div>
                </div>
                <div class="table-row" >
                    <span class="label"><label for="id_front_page">Front Page ?</label></span>

                    <span class="top" id="id_front_page">
                        {{ form.front_page }}
                    </span>
                </div>
                <div class="table-row" >
                    <span class="label synopsis"><label for="id_synopsis">Synopsis</label></span>
                    <span class="data synopsis">{{form.synopsis}}</span>
                </div>
                <div class="table-row">
                    <div class="table-cell label"><label for="id_publish_by">Publish by</label></div>
                        <div class="table-cell">{{form.publish_by}}</div>
                </div>
                <div class="table-row">
                    <div class="table-cell"><label for="id_publish_by">Expire by</label></div>
                    <div class="table-cell">{{form.expire_by}}</div>
                </div>
            </div>
            <div class="buttons">
                {% block buttons %}
                    <input id='tp_cancel_form' item_id='' type="button" value="Cancel">
                    <input id='tp_reset_form' type="reset" value="Reset Form">
                    <input id='tp_save_form' type="submit" value="Save new Article">
                {% endblock %}
            </div>
        </form>
</div>
{% endblock %}

team_pages/templates/news/tp_delete_news.html
{% extends "news/tp_manage_news.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}
{% load sponsor_tags %}

{% block details %}
<div class="detail bordered">

    <h3>Deleting news article '{{headline}}'</h3>
    <form method="POST">
        {% csrf_token %}
        <div class="buttons">
            <input id='tp_cancel_form' item_id="{{form.instance.news_id}}" type="button" value="Cancel">
            <input id="tp_save_form"  type="submit" value="Confirm Deletion of this NewsArticle">
        </div>
    </form>
</div>
{% endblock %}

team_pages/templates/news/tp_edit_news.html
{% extends "news/tp_manage_news_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}


{% block Title %}
        Brantham Garage Sale - Team Page: Editing '{{form.instance.headline}}'
{% endblock %}

{% block details %}
{{form.media}}
<div class="detail bordered">
    {% if form %}
        {% if form.published == True %}
        <div class="warning">
            Already Published
        </div>
    {% endif %}
        <form method="post">
            {%csrf_token%}
            <div class="table">
                {% if form.non_fields_errors %}
                <div class="errorList">
                        {{ form.non_field_errors }}
                </div>
                {% endif %}
                <div class="table-row" >
                    <span class="table-cell label"><label for="id_headline">Headline</label></span>
                    <span class="data">
                            {% if form.headline.errors %}
                            <div class="errorList">
                                    {{ form.headline.errors }}
                            </div>
                            {% endif %}
                        {{form.headline}}</span>
                </div>
                <div class="table-row heading" >
                    <div class="table-cell label" ><label for="id_content">Content</label></div>
                    <div class="content data">
                            {% if form.content.errors %}
                            <div class="errorList">
                                    {{ form.content.errors }}
                            </div>
                            {% endif %}
                            {{form.content }}
                   </div>
                </div>
                <div class="table-row" >
                    <span class="label"><label for="id_front_page">Front Page ?</label></span>

                    <span class="top" id="id_front_page">
                        {{ form.front_page }}
                    </span>
                    <span class="label synopsis"><label for="id_synopsis">Synopsis</label></span>
                    <span class="data synopsis">
                            {% if form.synopsis.errors %}
                            <div class="errorList">
                                    {{ form.synopsis.errors }}
                            </div>
                            {% endif %}
                            {{form.synopsis}}</span>
                </div>
                <div class="table-row">
                    <div class="table-cell label w25"><label for="id_publish_by">Publish by</label></div>
                        <div class="table-cell w25">
                            {% if form.publish_by.errors %}
                            <div class="errorList">
                                    {{ form.synopsis.publish_by }}
                            </div>
                            {% endif %}
                            {{form.publish_by}}</div>
                        {% if form.expire_by is not None %}
                    <div class="table-cell w25"><label for="id_expire_by">
                            Expire by</label></div>
                    <div class="table-cell w25">
                            {% if form.expire_by.errors %}
                            <div class="errorList">
                                    {{ form.expire_by.errors }}
                            </div>
                            {% endif %}
                            {{form.expire_by}}</div>
                        {% endif %}
                </div>
            </div>
            <div class="buttons">
                    <input id='tp_cancel_form' item_id='' type="button" value="Cancel">
                    <input id='tp_reset_form' type="reset" value="Reset to Initial">
                    <input id='tp_save_form' type="submit" value="Save Edits">
            </div>
        </form>
</div>
{% endif %}
{% endblock %}

team_pages/templates/news/tp_manage_news.html
{% extends "news/tp_manage_news_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block Title %}
        Brantham Garage Sale - Team Page: Manage News
{% endblock %}

{% block details %}

<div class="detail bordered">

</div>
{% endblock %}

team_pages/templates/news/tp_manage_news_base.html
{% extends "team_pages_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block PageScripts%}
<script type="text/javascript" src="{% static 'team_pages/js/news_page.js' %}"></script>
{% endblock %}

{% block SnappableSections %}
<script>
    const patterns = new Map([
    {% for path in patterns %}
        {% if forloop.last %}
           ['{{path.action}}', '{{path.regex | safe}}'] ]
        {% else %}
           ['{{path.action}}', '{{path.regex | safe }}'],
        {% endif %}
    {% endfor %}
    );
</script>
<div class="event_sub_data">
    {% block sublist %}
        <div id="id_article_list" class="sublist bordered">
            <div id="id_al_toolbar" class="actions">
                <ul>
                   <li><span id="tp-create" action="create" >&#127381;</span></li>  <!-- New Icon -->
                   <li><span id ="tp-filters" >&#9881;</span></li>  <!-- Gear Icon -->
                </ul>
                    <span id="filter-pop-up" style="display:none;">
                        <ul id="ListOptions">
                            <li><input checked
                                       tp-fragment="!Xpublished"
                                       tp-pair="id_include_unpublished"
                                              id="id_include_published" type="checkbox" />
                                <label for="id_include_published">Include Published</label></li>
                            <li><input
                                              tp-fragment="!XNotPublished"
                                                tp-pair="id_include_published"
                                              id="id_include_unpublished" type="checkbox" />
                                <label for="id_include_unpublished" >Include Unpublished</label>
                            <hr>
                            <li><input checked
                                              tp-fragment="!XFrontPage"
                                              tp-pair="id_include_not_front_page"
                                              id="id_include_front_page" type="checkbox" />
                            <label for="id_include_front_page">Include Front page</label>
                            <li><label><input checked
                                              tp-fragment="!XNotFrontPage"
                                              tp-pair="id_include_front_page"
                                              id="id_include_not_front_page" type="checkbox" />Include Not Front Page</label>
                            <hr>
                            <li><label><input id="id_include_expired"
                                              tp-fragment="expired"
                                              type="checkbox" />Include Expired</label>
                        </ul>
                        <input type="button" id="popup-button" onclick="save_list_options()" value="Save"/>
                    </span>
            </div>
            <table id="id_entry_list">
                <tr class="heading">
                    <th>Headline</th>
                    <th>Publish By</th>
                    <th>Expire By</th>
                    <th id="id_FrontPage">Frontpage ?</th>
                    <th id="id_Published">Published ?</th>
                    <th></th>
                </tr>
                <tbody id='tp_tbody_item_list'>
                {% for item in sub_list_data %}
                <tr class="data-row {% cycle 'odd' 'even' %}">
                    <td>{{ item.headline}}</td>
                    <td>{{ item.publish_by | date:'d m Y' }}</td>
                    <td>{{ item.expire_by | date:'d m Y' }}</td>
                    <td>{% if item.front_page %} &#x2705;{%else%}&#x274E{% endif %}</td>
                    <td>{% if item.published %} &#x2705;{%else%}&#x274E{% endif %}</td>
                    <td class="icons">
                        <span tp_row_id="{{item.id}}" tp_action="view">&#x1F50D;</span>
                        {% if not item.is_live %}
                            <span tp_row_id="{{item.id}}" tp_action="edit">&#x270E;</span>
                        {% endif %}
                        {% if perms.News.can_publish_news and item.can_be_published %}
                            <span tp_row_id="{{item.id}}" tp_action="publish">&#128424;</span>
                        {% endif %}
                        {% if perms.News.can_publish_news and item.published %}
                            <span tp_row_id="{{item.id}}" tp_action="publish">&#128721;</span>
                        {% endif %}
                        {% if perms.News.delete_news and not item.is_live %}
                            <span tp_row_id="{{item.id}}" tp_action="delete">&#128465;</span>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    {% endblock %}
    {% block details %}

    {% endblock %}
</div>
{% endblock %}

team_pages/templates/news/tp_view_news.html
{% extends "news/tp_manage_news_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block Title %}
        Brantham Garage Sale - Team Page: Viewing '{{form.instance.headline}}'
{% endblock %}

{% block details %}

<div class="detail bordered">
        {% if form.instance.published == True %}
        <div class="warning">
            Already Published
        </div>
        {% endif %}
        <form method="post">
            {%csrf_token%}
            <div class="table">
                <div class="table-row" >
                    <span class="table-cell label"><label for="id_headline">Headline</label></span>
                    <span class="data">{{form.instance.headline}}</span>
                </div>
                <div class="table-row heading" >
                    <div class="table-cell label" ><label for="id_content">Content</label></div>
                    <div class="content data">
                            {{form.instance.content.html | safe}}
                   </div>
                </div>
                <div class="table-row" >
                    <span class="label"><label for="id_front_page">Front Page ?</label></span>

                    <span class="top" id="id_front_page">

                        {% if form.instance.front_page %} &#x2705;{%else%}&#x274E{% endif %}
                    </span>
                    <span class="label synopsis"><label for="id_synopsis">Synopsis</label></span>
                    <span class="data synopsis">{{form.instance.synopsis}}</span>
                </div>
                <div class="table-row">
                    <div class="table-cell label w25"><label for="id_publish_by">Publish by</label></div>
                        <div class="table-cell w25">{{form.instance.publish_by}}</div>
                        {% if form.instance.expire_by is not None %}
                    <div class="table-cell w25"><label for="id_publish_by">Expire by</label></div>
                    <div class="table-cell w25">{{form.instance.expire_by}}</div>
                        {% endif %}
                </div>
            </div>
            <div class="buttons">
                {% block buttons %}
                    <input id='tp_cancel_form' item_id='' type="button" value="Cancel">
                {% endblock %}
            </div>
        </form>
</div>
{% endblock %}