GarageSale/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from .views import general_views

from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", general_views.home, name="home"),
    path("newhome", TemplateView.as_view(template_name='home.html'), name="NewHome"),
    path("getInvolved", RedirectView.as_view(url=reverse_lazy('Location:view'))),
#    path("getInvolved", include('Location.urls'), name="getInvolved"),
    path('about_us', TemplateView.as_view(template_name='aboutUs.html'), name='AboutUs'),
    path('contact', TemplateView.as_view(template_name='contact.html'), name='ContactUs'),
    path('privacy', TemplateView.as_view(template_name='privacy_policy.html'), name='Privacy'),
    path('blind_auction', TemplateView.as_view(template_name='blind_auction.html'), name='BlindAuction'),
    path('donate', TemplateView.as_view(template_name='donate.html'), name='Donate'),
    path('location/', include('Location.urls')),
    path('team_page/', include('team_pages.urls', 'TeamPages')),
    path('news/', include('News.urls')),
    path('user/', include('user_management.urls')),
#    path('billboard/', include('Billboard.urls')),
#    path('sale_location/', include('SaleLocation.urls')),

    # path('test/<int:case>/', views.testing, name='test'),
    path('sponsors/', include('Sponsors.urls')),
    path('CraftMarket/', include('CraftMarket.urls')),
    path('Account/', include('Accounts.urls')),

    path('mapping/', include('DjangoGoogleMap.urls')),
    path('summernote/', include('django_summernote.urls')),

    path("GoogleDrive/", include('GoogleDrive.urls', namespace='GoogleDrive') ),

]


if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

News/urls.py
#!/usr/bin/env python
# coding=utf-8
"""
    GarageSale.urls.py : 

Summary :
    
    
Use Case :
    
    
Testable Statements :
    ...0
"""
from .views import Article, news_page,news_letter_subscribe

from django.urls import path

app_name = "News"

urlpatterns = [
    path("", news_page, name="NewsPage"),
    path("article/<slug:slug>", Article.as_view(), name="article"),
    path("subscribe", news_letter_subscribe, name='subscribe'),
]

user_management/urls.py
#!/usr/bin/env python
# coding=utf-8

from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = 'user_management'

urlpatterns = [
    path("register", views.UserRegistration.as_view(), name="register"),
    path("verify/<uuid:uuid>/", views.user_verify, name='verify'),
    path('resendregistation/<uuid:uuid>/', views.resend_registration_link,
         name='resend_verify'),
    path("login", views.Login.as_view(), name="login"),
    path("identify", views.identify, name="identify"),
    path('logoff', views.logoff, name='logoff'),
    path('pwd_change', views.ChangePassword.as_view(), name='change_password'),
    path('pwd_reset', views.ResetPasswordApply.as_view(),
         name='reset_password_application'),
    path('reset/<uuid:uuid>/', views.PasswordResetEnterNew.as_view(),
         name='password_reset_prompt_new'),
    path('guest', views.GuestApplication.as_view(), name='guest_application'),
    path('input_short_code/<int:short_code_id>/',
         views.InputShortCode.as_view(), name='input_short_code'),
    path('resend/<int:short_code_id>/', views.resend_short_code, name='resend'),
    path('error/<int:short_code_id>/', views.guest_error, name='guest_error'),

]

user_management/views.py
import datetime
import logging
from typing import Type
from uuid import uuid1

from django.contrib.auth.base_user import AbstractBaseUser
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import login as login_user
from django.http import HttpResponseServerError, HttpRequest
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import redirect, reverse
from django.template.response import TemplateResponse
from django.utils.html import escape
from django.db import transaction
from django.shortcuts import resolve_url
from django.views.generic import View
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.contrib.auth import authenticate

from . import forms
from . import models
from .models import RegistrationVerifier, GuestVerifier, PasswordResetApplication, UserVerification, UserExtended, \
    AdditionalData

from .apps import appsettings, settings
from django.contrib.auth import get_user_model, login, logout, update_session_auth_hash

from .models import RegistrationVerifier
import logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# ToDo - show password Help on registration, and validate password format
# ToDo - test password Reset stuff
# ToDo - Remove old templates - retest first
# ToDo - Rename the views - they are confusing

def send_register_verification_email(incoming_request, email, url):
    # Send email to the new user_management with a link to the verification view
    email_template = "email/verify_email.html"

    base_url = incoming_request.scheme + r'://' + incoming_request.get_host()
    html_content = TemplateResponse(incoming_request, email_template,
                                    context={'base_url': base_url,
                                             'url': url}).rendered_content
    # Extract Application settings from the APPS_SETTING dictionary with defaults
    site_name = appsettings().get('user_management', {}).get('SITE_NAME', '')
    sender = appsettings().get('user_management', {}).get('EMAIL_SENDER', None)
    sender = sender if sender else settings.EMAIL_HOST_USER
    non_html = (f'Thank for registering for a user account on {site_name}\n'
                f'To confirm your registration - please copy/paste the following link into your browser:\n'
                f'{url}\n'
                f'This link will expire in ')
    msg = EmailMultiAlternatives(subject=f'{site_name}: Verify registration of your account',
                                 from_email=f'{sender}',
                                 to=[email])
    msg.attach_alternative(non_html, 'text/plain')
    msg.attach_alternative(html_content, 'text/html')
    msg.send()


def send_guest_verification_email(request, email=None, short_code=None, template=None,
                                  sender=None):
    """Send an email with the one time code"""
    html_content = TemplateResponse(
        request=request,
        template=template,
        context={'code': short_code.short_code,
                 'lifetime': short_code.short_code_lifetime,
                 },
    ).rendered_content

    site_name = appsettings().get('user_management', {}).get('SITE_NAME', '')
    sender = sender if sender else appsettings().get('user_management', {}).get('EMAIL_SENDER', None)
    sender = sender if sender else settings.EMAIL_HOST_USER

    msg = EmailMultiAlternatives(subject=f'{site_name}: Guest Account One time code',
                                 from_email=f'{sender}',
                                 to=[email])
    msg.attach_alternative(f'Your one time code is {short_code.short_code} - '
                           f'please enter this value into the website',
                           'text/plain')
    msg.attach_alternative(html_content, 'text/html')
    msg.send()


def guest_error(incoming_request, short_code_id=None):
    """View to display error page for guest logins"""
    next = incoming_request.GET.get('next', '/')

    try:
        code_inst = GuestVerifier.objects.get(pk=short_code_id)
    except GuestVerifier.DoesNotExist:
        logger.info(f'Invalid Short Code {short_code_id} sent to error page !')
        redirect_url = incoming_request.GET.get('next', '/')
        return redirect( reverse('user_management:guest_application') + '?next=' + redirect_url )


    match code_inst.reason_code:
        case 'expired':
            pre_form = 'Your existing short code expired'
        case 'entry_error':
            pre_form = 'You failed to enter the correct short code after 3 attempts.'
        case _:
            pre_form = ''

    form = forms.GuestApplicationError()

    return TemplateResponse(incoming_request,
                            'generic_with_form.html',
                            context=form.form_context(
                                action_path=resolve_url('user_management:resend', short_code_id=short_code_id),
                                pre_form=pre_form,
                                next=next))


def resend_short_code(incoming_request, short_code_id=None):
    """"Simple view to resend a new short-code - use existing short_code
        as the original data for the next
    """
    email_template = "email/guest_short_code-email.html"

    next_url = incoming_request.GET.get('next', '/')
    try:
        inst: GuestVerifier = GuestVerifier.objects.get(id=short_code_id)
    except GuestVerifier.DoesNotExist:
        logger.info(f'Invalid Short Code {short_code_id} sent to resend page !')
        redirect_url = incoming_request.GET.get('next', '/')
        return redirect( reverse('user_management:guest_application') + '?next=' + redirect_url )

    email = inst.email
    GuestVerifier.remove_expired(email=email, _any=True)

    new_inst = GuestVerifier.add_guest_verifier(email=email)
    new_inst.reason_code='resend'
    new_inst.save()

    send_guest_verification_email(incoming_request, email=email, short_code=new_inst, template=email_template)

    return redirect(reverse('user_management:input_short_code',
                            kwargs={'short_code_id': new_inst.pk}) + f'?next={next_url}')


def resend_registration_link(incoming_request, uuid):
    """"Simple view to resend a new short-code - use existing short_code
        as the original data for the next
    """
    next_url = incoming_request.GET.get('next', '/')

    verifier_inst = RegistrationVerifier.objects.get(uuid=uuid)

    user_model:Type[UserExtended|AbstractBaseUser] = get_user_model()
    try:
        user = user_model.objects.get(email=verifier_inst.email)
    except user_model.DoesNotExist:
        raise ObjectDoesNotExist('User does not exist')

    email = verifier_inst.email
    if user.is_guest:
        try:
            additional = verifier_inst.AdditionalData.objects.values().get()
        except AdditionalData.DoesNotExist:
            raise ObjectDoesNotExist('Registration AdditionalData does not exist')
    else:
        additional = {}

    verifier_inst.delete()

    verifier_inst = RegistrationVerifier.add_registration_verifier(user=user, **additional)

    url = verifier_inst.link_url(request=incoming_request, next_url=next_url)

    send_register_verification_email(email=verifier_inst.email, incoming_request=incoming_request, url=url)

    return TemplateResponse(incoming_request, 'generic_response.html',
                            context={'msg': 'A new registration link has been sent.<br>'
                                            f'Please check your email {UserRegistration.obfuscate_email(verifier_inst)} for a verification link which will '
                                            'complete the registration process.<br>'
                                     'If the email doesn\'t arrive - please check your spam email folder'})




class GuestApplication(View):
    email_template = "email/guest_short_code-email.html"

    def get(self, incoming_request):
        redirect_url = incoming_request.GET.get('next', '/')

        form = forms.GuestRequestForm()
        return TemplateResponse(incoming_request,
                                template='generic_with_form.html',
                                context=form.form_context(next=redirect_url))

    def post(self, incoming_request: HttpRequest):
        next = incoming_request.GET.get('next', '/')

        form = forms.GuestRequestForm(incoming_request.POST)
        if not form.is_valid():
            return TemplateResponse(incoming_request,
                                    'generic_with_form.html',
                                    context=form.form_context(next=next)
                                    )

        email = form.cleaned_data['email']

        # We know the data is a valid email - remove old entries and add a new entry
        GuestVerifier.remove_expired(email=email)
        code = GuestVerifier.add_guest_verifier(email=email)

        send_guest_verification_email(incoming_request,
                                      email=form.cleaned_data['email'],
                                      short_code=code,
                                      template=self.email_template)

        return redirect(resolve_url('user_management:input_short_code', short_code_id=code.pk) + f'?next={next}')


class InputShortCode(View):

    @staticmethod
    def _obfuscate_email(short_code_inst: GuestVerifier) -> str:
        email = short_code_inst.email
        tld = email.split('.')[-1]
        name, domain = email.split('@')[0], email.split('@')[1]
        return name[0:4].rjust(len(name), '*') + '@' + domain[0:4].rjust(len(domain), '*') + '.' + tld

    def get(self, incoming_request, short_code_id):
        next = incoming_request.GET.get('next', '/')
        try:
            code_inst = GuestVerifier.objects.get(pk=short_code_id)
        except GuestVerifier.DoesNotExist:

user_management/templates/ShortCodeInput.html
{% extends "_snap_slider_base.html" %}
{% load static %}
{% load user_management_tags %}

 {% block additionalStyles%}
     {{ block.super }}
 <style>
input[type='text']:where([autocomplete=one-time-code]) {
  --otp-digits: 7;
  --otp-ls: 2ch;
  --otp-gap: 1.25;
  --otp-bg: lightblue;

  /* private consts */
  --_otp-bgsz: calc(var(--otp-ls) + 1ch);
  --_otp-digit: 0;

  all: unset;
  background:
  linear-gradient(90deg,
    var(--otp-bg, #BBB) calc(var(--otp-gap) * var(--otp-ls)),
    transparent 0),
    linear-gradient(90deg,
    var(--otp-bg, #555) calc(var(--otp-gap) * var(--otp-ls)),
    transparent 0
  );
  background-position: calc(var(--_otp-digit) * var(--_otp-bgsz)) 0, 0 0;
  background-repeat: no-repeat, repeat-x;
  background-size: var(--_otp-bgsz) 100%;
  caret-color: var(--otp-cc, #222);
  caret-shape: block;
  color:black;
  clip-path: inset(0% calc(var(--otp-ls) / 2) 0% 0%);
  font-family: ui-monospace, monospace;
  font-size: var(--otp-fz, 1rem);
  inline-size: calc(var(--otp-digits) * var(--_otp-bgsz));
  letter-spacing: var(--otp-ls);
  padding-block: var(--otp-pb, 1ch);
  padding-inline-start: calc(((var(--otp-ls) - 1ch) / 2) * var(--otp-gap));
  font-family: ui-sans-serif, system-ui, sans-serif;
}
</style>
{% endblock %}

{% block sidebar %}
        <div class="sidebar entry direct tooltip" item="Homepage" xmlns="http://www.w3.org/1999/html">
            <a href="{% url 'home' %}">
                <img class="sidebar icon" alt="Home Page" id='id_home_page' src={% static "GarageSale/images/icons/menu/home-svgrepo-com.svg" %} >
                <label for="id_team">Home Page</label></a>
                <span class="tooltiptext right arrow">Return to Home Page</span>
        </div>
{%  endblock %}

{% block SnappableSections %}
        {% if pre_form %}
            <div id="_preform">
                {{ pre_form }}
            </div>
        {% endif %}
    <h2>Enter the short code sent to {{obfuscated_email}}</h2>
    <div class="form">
        <div style="font-size:90%;margin:1rem 0;">
            If you can't find the email please check your junk or spam folders for an email from Website@BranthamGarageSale.org.uk.
        </div>
        <form method="POST" action="{{action}}">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div id="InvalidAttempt">
                    {% for err in form.non_field_errors %}
                        {% if retry_count < max_retry %}
                        {{err}} : {{retry_count}} Attempts remaining
                        {% else %}
                            {{err}}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            {{ form.email }}
            <strong>{{form.short_code.label}}</strong> {{ form.short_code }}

            <div class="buttons">
                <span style="float:left">
                    <input type="submit" id='id_Continue' value="Continue">
                </span>

                <span style="float:left; margin-left:20rem;">
                    <input type="button" id='id_Resend' onclick="resend_short_code()" value="Send a new Code">
                    <script lang="javascript" type="text/javascript">
                            function resend_short_code()
                            {
                                window.location.replace( "{{ resend_url }}" );
                            }
                    </script>
                </span>
            </div>
            <script>
                const input = document.querySelector('[autocomplete=one-time-code');
input.addEventListener('input', () => input.style.setProperty('--_otp-digit', input.selectionStart));
            </script>
        </form>
    {% if post_form %}
        <div class="post-form">
            {{post_form | safe}}
        </div>
    {% endif %}
    </div>
{% endblock %}

user_management/templates/__login.html
{% extends "_base_with_toolbar.html" %}
{% load static %}
{% load user_management_tags %}

{% block body %}
    <div class="form">
            <form method="POST" action="{% url 'user_management:login' %}?redirect={{ redirect }}" >
                {% csrf_token %}
                <table>
                    {{form.as_table}}
                </table>
                <div class="buttons">
                    <input type="button" onclick="cancel_login()" value="Cancel">
                    <input type="button" onclick="register()" value="Register">
                    <input type="submit" value="Login">
                </div>
            </form>
        <script>
            /* Implement register button */
            function register()
            {
                window.location.replace( '/user/register' );
            }

            /* Implement cancel button as a simple return to the GetInvolved page */
            function cancel_Login()
            {
                window.location.replace( '{{redirect}}' );
            }
         </script>
        <div class="post_form">
            Problems logging in - do you need to <a href="{%url 'user_management:reset_password_application' %}?redirect={{ redirect }}">Password reset</a> ?.
        </div>
    </div>
{% endblock %}

user_management/templates/__password_change_done.html
{% extends "_base_with_toolbar.html" %}
{% load static %}
{% load user_management_tags %}
{% block head-extra %}
<meta http-equiv="refresh" content="15;url={{ redirect }}" />
{% endblock%}

{% block body %}
    <div class="form">
            <h2>Password Changed Successfully</h2>
            Your password has now been changed - you should continue where you left off in a few seconds.
            If not press the button below.
            <form method="GET" action="{{ redirect }}" >
            <div class="buttons">
                <input type="submit" value="Continue">
            </div>
        </form>
    </div>
{% endblock %}

user_management/templates/__password_reset_sent.html
{% extends "_base_with_toolbar.html" %}
{% load static %}
{% load user_management_tags %}

{% block body %}
<div>
    An Password reset email has been sent to you. Please check your email and click the button/link.
</div>
{% endblock %}

user_management/templates/__reset_password_apply.html
{% extends "_base_with_toolbar.html" %}
{% load static %}
{% load user_management_tags %}

{% block body %}
<H2>
    Password Reset Application
</H2>
<div class="form">
    <form method="POST" action="{% url 'user_management:reset_password_application' %}?redirect={{redirect}}">
        <table>
            {% csrf_token %}
            {{ form }}
        </table>
        <div class="buttons">
            <input type="reset" value="Reset Form">
            <input type="button" onclick="cancel_PasswordReset()" value ="Cancel">
            <input type="submit" value="Password Reset">
        </div>
    </form>
    <script>
        /* Implement cancel button as a simple return to the GetInvolved page */
        function cancel_PasswordReset()
        {
            window.location.replace( {{redirect}} );
        }
    </script>
</div>

{% endblock %}

user_management/templates/generic_response.html
{% extends "_base_with_toolbar.html" %}
{% load static %}
{% load user_management_tags %}

{% block head-extra %}
    {% if redirect %}
        <meta http-equiv="refresh" content="10;url={{ redirect }}" />
    {% endif %}
{% endblock%}

{% block body %}
    <div class="msg">
        {{msg | safe}}
    </div>
    {% if redirect %}
        <div>
            If this form does not automatically redirect, then click the button below.
        </div>
        <form method="GET" action="{{ redirect }}" >
            <div class="buttons">
                <input type="submit" value="Continue">
            </div>
        </form>
    {% endif %}

{% endblock %}

user_management/templates/generic_with_form.html
{% extends "_snap_slider_base.html" %}
{% load static %}
{% load user_management_tags %}
<script>
    function fn_name(str)
    {
        return str.replace(' ','_').toLowerCase()
    }
</script>

{% block sidebar %}
        <div class="sidebar entry direct tooltip" item="Homepage" xmlns="http://www.w3.org/1999/html">
            <a href="{% url 'home' %}">
                <img class="sidebar icon" alt="Home Page" id='id_home_page' src={% static "GarageSale/images/icons/menu/home-svgrepo-com.svg" %} >
                <label for="id_team">Home Page</label></a>
                <span class="tooltiptext right arrow">Return to Home Page</span>
        </div>
{%  endblock %}

{%  block SnappableSections %}
    {% if form_title %}
        <h2>{{form_title}}</h2>
    {% endif %}
    <div class="form">
        {% if pre_form %}
            <div class="pre-form">
                {{pre_form | safe }}
             </div>
        {% endif %}
        <form method="{{method}}" action="{{action}}">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <div class="buttons">
                {% for button in buttons %}
                    {% if button.redirect %}
                        <script>
                            function {{button.name|lower|cut:' '}}_redirect()
                            {
                                window.location.replace( '{{button.redirect}}' );
                            }
                        </script>
                        <input type="{{button.type}}" onclick="{{button.name|lower|cut:' '}}_redirect()"  value="{{button.name}}">
                   {% else %}
                        <input type="{{button.type}}" value="{{button.name}}">
                   {% endif %}
                {% endfor %}

            </div>
        </form>
    {% if post_form %}
        <div class="post-form">
            {{post_form | safe}}
        </div>
    {% endif %}
    </div>
{% endblock %}

user_management/templates/identify.html
{% extends "_snap_slider_base.html" %}
{% load static %}
{% load user_management_tags %}

{% block Title %}
Brantham Garage Sale - Identifying user
{% endblock %}

{% block sidebar %}

    <!-- Do we need a cms ??? -->
    <div class="sidebar entry tooltip" item="home" id='home' xmlns="http://www.w3.org/1999/html">
        <img class="sidebar icon" alt="Back Home" id='id_home_icon' src={% static 'GarageSale/images/icons/menu/home-svgrepo-com.svg' %}>
        <label for="id_home_icon">Back Home</label>
        <span class="tooltiptext arrow right">Go Back Home</span>
    </div>
{%  endblock %}

{% block SnappableSections %}
    <script type="text/javascript">
    function login() { window.location.replace( "/user/login?next={{next|safe}}" ); }
    function guest() { window.location.replace( "/user/guest?next={{next|safe}}" ); }
</script>

<div class="form" style="width:50%;margin:auto;text-align:center;padding:5px;">
    <H1 style="margin-top:10px">Identifying you</H1>
    In order to manage your locations we need to know who you are.
    <form method="POST">
    <input type="hidden" name="next">
    <div class="buttons">
    <input type="button" value="Login" onclick="login()">
    <input type="button" value="Continue as a Guest" onclick="guest()">
    </div>
</form>

</div>
{% endblock %}

user_management/templates/password_change.html
{% extends "_base_with_toolbar.html" %}
{% load static %}
{% load user_management_tags %}

{% block body %}
    <div class="form">
        <form method="POST" action="{% url 'user_management:change_password'%}?redirect={{redirect}}" >
            <table>
            {% csrf_token %}
            {{ form.as_table }}
            </table>
            <div class="buttons">
                <input type="button" onclick="cancel_pwd_change()" value="Cancel">
                <input type="submit" value="Change Password">
            </div>
        </form>
    </div>
<script>
        function cancel_pwd_change()
        {
            window.location.replace( '{{redirect}}' );
         }
</script>
{% endblock %}

user_management/templates/password_change_done.html
{% extends "_base_with_toolbar.html" %}
{% load static %}
{% load user_management_tags %}
{% block head-extra %}
<meta http-equiv="refresh" content="15;url={{ redirect }}" />
{% endblock%}

{% block body %}
    <div class="form">
            <h2>Password Changed Successfully</h2>
            Your password has now been changed - you should continue where you left off in a few seconds.
            If not press the button below.
            <form method="GET" action="{{ redirect }}" >
            <div class="buttons">
                <input type="submit" value="Continue">
            </div>
        </form>
        <script>
            /* Implement cancel button as a simple return to the GetInvolved page */
            function cancel_Login()
            {
                window.location.replace( '{{redirect}}' );
            }
         </script>
    </div>
{% endblock %}

user_management/templates/pwd_change.html
{% extends "_base_with_toolbar.html" %}
{% load static %}
{% load user_management_tags %}

{% block body %}
    <div class="form">
        <form method="POST" action="{% url 'user_management:change_password' %}">
            <table>
            {% csrf_token %}
            {{ form.as_table }}
            </table>
            <div class="buttons">
                <input type="button" onclick="cancel_pwd_change()" value="Cancel">
                <input type="submit" value="Change Password">
            </div>
        </form>
    </div>
<script>
        function cancel_pwd_change()
        {
            window.location.replace( '{% url "getInvolved" %}' );
         }
</script>
{% endblock %}

user_management/templates/register_user_form.html
<h2>User Registration</h2>

<form method="post" action="{% url 'user_management:register' %}">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <div class="buttons">
        <input type="button" onclick='cancel_registration()' value="Cancel">
        <input type="reset" value="Reset">
        <input type="button" onclick='login()' value="Login">
        <input type="submit" value="Register">
    </div>
</form>
<script>
        /* Implement cancel button as a simple return to the GetInvolved page */
        function cancel_registration()
        {
            window.location.replace( '{{redirect}}' );
        }

        /* Implement Login button as a simple return to the GetInvolved page */
        function login()
        {
            window.location.replace( '{% url "user_management:login" %}'?redirect={{redirect}} );
         }
</script>

user_management/templates/register_waiting.html
{% extends "_base_with_toolbar.html" %}
{% load static %}
{% load user_management_tags %}

{% block body %}

    Check your emails for a verification link

{% endblock %}

user_management/templates/user_menu.html
{% load user_management_tags %}
{% if not request.user.is_authenticated %}
    <li>{% login_form_link request.path %}</li>
    <li>{% register_form_link request.path %}</li>
{% elif request.user.is_active %}
    <li><a href="{% url 'user_management:change_password' %}?redirect={{request.path}}">Change Password</a></li>
    <li><a href="{% url 'user_management:logoff' %}?redirect={{request.path}}">Logoff</a></li>
{% else %}
    <li>Waiting for email confirmation</li>
{%endif%}