Accounts/urls.py
from django.urls import path, include

from . import views

app_name = "Account"

urlpatterns = [
    path('upload/', views.upload_transactions, name='upload_transactions'),
    path('uploadErrors/', views.UploadErrorList.as_view(), name='UploadErrorList'),
    path('uploadErrors/<int:account_id>/', views.UploadErrorList.as_view(), name='UploadErrorList'),
    path('uploadErrors/<int:account_id>/<int:upload_id>/', views.UploadErrorList.as_view(), name='UploadErrorList'),

    path('report/transactions/', views.TransactionList.as_view(), name='TransactionList'),
    path('report/transactions/<int:account_id>/', views.TransactionList.as_view(), name='TransactionList'),

    path('financialyear/', views.FinancialYearList.as_view(), name='FinancialYearList'),
    path('financialyear/view/<str:fy>/',views.FinancialYearDetail.as_view(), name='FinancialYearDetail'),
    path('fincialyear/edit/<str:fy>/', views.FinancialYearEdit.as_view(), name='FinancialYearEdit'),
    path('financialyear/close/<str:fy>/', views.FinancialYearClose.as_view(), name='FinancialYearClose'),
    path( 'financialyear/create/', views.FinancialYearCreate.as_view(), name='FinancialYearCreate'),

    path('report/', views.FinancialReport.as_view(), name='report'),
    path('report/<int:account_id>/', views.FinancialReport.as_view(), name='report'),

    #ToDo - a single REST API with actions - maybe ?
    path('get_category_list/<int:transaction_id>/', views.restapi.get_categories, name='get_categories'),
    path('get_child_categories/<int:transaction_id>/', views.restapi.get_child_categories, name='get_child_categories'),
    path('edit_transaction/<int:transaction_id>/', views.restapi.edit_transaction, name='edit_transaction'),
    path('edit_split/<int:transaction_id>/', views.restapi.edit_split, name='edit_split'),
    path('add_split/<int:transaction_id>/', views.restapi.add_split, name='edit_split'),
    path( 'delete_transaction/<int:transaction_id>/', views.restapi.delete_transaction, name='delete_transaction')
]

GarageSale/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from .views import general_views

from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", general_views.home, name="home"),
    path("newhome", TemplateView.as_view(template_name='home.html'), name="NewHome"),
    path("getInvolved", RedirectView.as_view(url=reverse_lazy('Location:view'))),
#    path("getInvolved", include('Location.urls'), name="getInvolved"),
    path('about_us', TemplateView.as_view(template_name='aboutUs.html'), name='AboutUs'),
    path('contact', TemplateView.as_view(template_name='contact.html'), name='ContactUs'),
    path('privacy', TemplateView.as_view(template_name='privacy_policy.html'), name='Privacy'),
    path('blind_auction', TemplateView.as_view(template_name='blind_auction.html'), name='BlindAuction'),
    path('donate', TemplateView.as_view(template_name='donate.html'), name='Donate'),
    path('location/', include('Location.urls')),
    path('team_page/', include('team_pages.urls', 'TeamPages')),
    path('news/', include('News.urls')),
    path('user/', include('user_management.urls')),
#    path('billboard/', include('Billboard.urls')),
#    path('sale_location/', include('SaleLocation.urls')),

    # path('test/<int:case>/', views.testing, name='test'),
    path('sponsors/', include('Sponsors.urls')),
    path('CraftMarket/', include('CraftMarket.urls')),
    path('Account/', include('Accounts.urls')),

    path('mapping/', include('DjangoGoogleMap.urls')),
    path('summernote/', include('django_summernote.urls')),

    path("GoogleDrive/", include('GoogleDrive.urls', namespace='GoogleDrive') ),

]


if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

News/urls.py
#!/usr/bin/env python
# coding=utf-8
"""
    GarageSale.urls.py : 

Summary :
    
    
Use Case :
    
    
Testable Statements :
    ...0
"""
from .views import Article, news_page,news_letter_subscribe

from django.urls import path

app_name = "News"

urlpatterns = [
    path("", news_page, name="NewsPage"),
    path("article/<slug:slug>", Article.as_view(), name="article"),
    path("subscribe", news_letter_subscribe, name='subscribe'),
]

team_pages/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from GarageSale.views.template_views import TemplatesView
from . import views
from . import stats_view

app_name = 'TeamPages'
urlpatterns = [
    path('', views.TeamPage.as_view(), name='Root'),
    path('<int:event_id>/', views.TeamPage.as_view(), name='EventRoot'),
    path('<int:event_id>/stats/', stats_view.event_stats, name='EventStats'),

    # TODO Rework without Generic Views = more trouble than they are worth
    path('motd/create/', views.MotDCreate.as_view(), {'action': '_create'}, name='MotdCreate', ),
    path('motd/<int:motd_id>/edit/', views.MotDEdit.as_view(), name='MotdEdit'),
    path('motd/<int:motd_id>/view/', views.MotDView.as_view(), name='MotdView'),
    path('motd/<int:motd_id>/delete/', views.delete_motd, name='MotdDelete'),

    path('news/', views.NewsRoot.as_view(), name='News'),
    path('news/create/', views.NewsCreate.as_view(), name='CreateNews'),
    path('news/<int:news_id>/edit/', views.NewsEdit.as_view(), name='EditNews'),
    path('news/<int:news_id>/view/', views.NewsView.as_view(), name='ViewNews'),
    path('news/<int:news_id>/publish/', views.PublishNews, name='PublishNews'),
    path('news/<int:news_id>/delete/', views.NewsDelete.as_view(), name='DeleteNews'),

    path('event/', views.TeamPage.as_view(), name='Event'),
    path('event/<int:event_id>/', views.TeamPage.as_view(), name='EventDisplay'),

    path('event/create/', views.EventCreate.as_view(), name='EventCreate'),
    path('event/<int:event_id>/edit/', views.EventEdit.as_view(), name='EventEdit'),
    path('event/<int:event_id>/view/', views.EventView.as_view(), name='EventView'),
    path('event/<int:event_id>/use/', views.event_use, name='EventUse'),
    path('event/<int:event_id>/ad_board/',views.ad_board_csv, name='EventAdBoard'),

    path('sponsor/<int:event_id>/', views.SponsorsRoot.as_view(), name='Sponsor'),
    path('sponsor/<int:event_id>/create/', views.SponsorCreate.as_view(), name='SponsorCreate'),
    path('sponsor/<int:sponsor_id>/view/', views.SponsorView.as_view(), name='SponsorView'),
    path('sponsor/<int:sponsor_id>/edit/', views.SponsorEdit.as_view(), name='SponsorEdit'),
    path('sponsor/<int:sponsor_id>/confirm/', views.SponsorConfirm.as_view(), name='SponsorConfirm'),
    path('sponsor/<int:sponsor_id>/delete/', views.SponsorDelete.as_view(), name='SponsorConfirm'),
    path("GoogleDrive/", TemplateView.as_view(template_name='GoogleDrive.html'), name='GoogleDrive'),
]

Accounts/models.py
import datetime
from decimal import Decimal

from gdstorage.storage import GoogleDriveStorage

from django.apps import apps
from django.conf import settings
from django.db import models
import re
import string

from django.db.models import Lookup, OuterRef, Subquery, F, Sum, Case, When, Value, Q, Exists, Count
from django.db.models.sql import Query
from django.template.defaultfilters import default
from django.utils.translation.reloader import translation_file_changed



def save_uploaded_file(instance, filename):
    return f'accounts/reports/{instance.account.natural_key()[0]}/{filename}'

class PublishedReports(models.Model):
    report_type = models.CharField(max_length=20)
    period_start = models.DateField()
    period_end = models.DateField()
    report_file = models.ForeignKey('GoogleDrive.DriveFile', on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-uploaded_at']
        indexes = [models.Index(fields=['report_type', 'period_start', 'period_end'])]

    def natural_key(self):
        return self.report_type, self.period_start, self.period_end

# Create your models here.
class AccountManager(models.Manager):
    def get_by_natural_key(self, bank_name, sort_code, account_number):
        return self.get(bank_name=bank_name, sort_code=sort_code, account_number=account_number)

class Account(models.Model):
    objects = AccountManager()
    bank_name = models.CharField(max_length=100)
    sort_code = models.CharField(max_length=100)
    account_number = models.CharField(max_length=100)
    starting_balance = models.DecimalField(max_digits=10, decimal_places=2)

    @property
    def last_transaction_number(self):
        return last if (last := Transaction.objects.filter(account=self).aggregate(models.Max('tx_number'))['tx_number__max']) else 0

    class Meta:
        ordering = ['bank_name']
    def __str__(self):
        return f'{self.bank_name}\nSort Code : {self.sort_code}\nAcc #:{self.account_number}'
    def natural_key(self):
        return self.bank_name, self.sort_code, self.account_number

class CategoryManager(models.Manager):
    def get_by_natural_key(self, category_name, *args, **kwargs):
        return self.get(category_name=category_name)

class Categories(models.Model):
    objects = CategoryManager()
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, null=True, blank=True)
    category_name = models.CharField(max_length=100, unique=True)
    credit_debit = models.CharField(choices=[('C','Credit'),('D','Debit')], max_length=1, default='C')

    class Meta:
        ordering = ['category_name']
        indexes = [models.Index(fields=['category_name']), models.Index(fields=['credit_debit'])]

    def natural_key(self):
        return [self.category_name]

    def __str__(self):
        return self.category_name


class FinancialYearManager(models.Manager):
    def current(self):
        return self.get(year_start__lte=datetime.date.today(), year_end__gte=datetime.date.today())
    def create_from_year(self, calendar_year):
        return self.create(year=f'{calendar_year}-{calendar_year+1}', year_start=datetime.date(calendar_year, 10, 1), year_end=datetime.date(calendar_year+1, 9, 30))
    def get_natural_key(self,year):
        return self.get(year=year)
    def get_transaction_list(self, account):
        return Transaction.objects.filter(account=account, financial_year=self).order_by('transaction_date')
    def overlap(self, period_start, period_end):
        """Return all the Financial Year that contain the period as provided"""
        return (FinancialYear.objects.
                    filter(
                            Q(year_start__lte=period_start, year_end__gte=period_start)| # Contains the start date
                            Q(year_start__lte=period_end, year_end__gte=period_end)|     # Contains the end date
                            Q(year_start__gt=period_start, year_end__lt=period_end)      # Is in the middle of the period
                    ).distinct('year_start').values_list('year', flat=True).order_by('year_start'))

class FinancialYear(models.Model):
    objects = FinancialYearManager()
    year = models.CharField(max_length=20)
    year_start = models.DateField()
    year_end = models.DateField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.year}  ({self.get_year_start_display()} to {self.get_year_end_display()})'
    def natural_key(self):
        return self.year

    def _get_date_display(self, date_item:datetime.date):
        return date_item.strftime('%d %b %Y')
    def get_year_start_display(self):
        return self._get_date_display(self.year_start)
    def get_year_end_display(self):
        return self._get_date_display(self.year_end)
    def is_complete(self):
        return self.year_end < datetime.date.today()

class UploadHistoryManager(models.Manager):
    def get_by_natural_key(self, account, start_date, end_date):
        account_id = Account.objects.get_by_natural_key(*account).id
        return self.get(account=account_id, start_date=start_date, end_date=end_date)
class UploadHistory(models.Model):
    class Meta:
        ordering = ['-uploaded_at']
        unique_together = [['account', 'start_date', 'end_date']]
        indexes = [models.Index(name='ByAccount',fields=['account']),
                   models.Index(name='ByDate', fields=['start_date', 'end_date']),
                   models.Index(name='ByUploadDate', fields=['uploaded_at'])]
    objects = UploadHistoryManager()
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def natural_key(self):
        return self.account.natural_key(), self.start_date, self.end_date
    def error_repr(self):
        return f'Upload {self.uploaded_at.strftime('%d/%m/%Y %H:%M')} by {self.uploaded_by} - {self.errors.count()} Error(s)'
    def error_count(self):
        return self.errors.count()

class UploadErrorManager(models.Manager):
    def get_by_natural_key(self, upload, transaction):
        upload_id = UploadHistory.objects.get_by_natural_key(*upload).id
        transaction_id = Transaction.objects.get_by_natural_key(*transaction).id
        return self.get(upload_history=upload_id, transaction=transaction_id)

class UploadError(models.Model):
    class Meta:
        indexes = [models.Index(name='ByTransaction', fields=['transaction']),
                   models.Index(name='ByUploadHistory', fields=['upload_history'])]
    objects = UploadErrorManager()
    transaction = models.ForeignKey('Transaction', on_delete=models.CASCADE)
    upload_history = models.ForeignKey(UploadHistory, related_name='errors', on_delete=models.CASCADE)
    error_message = models.CharField(max_length=200)
    def natural_key(self):
        return self.upload_history.natural_key(), self.transaction.natural_key()

class TransactionManager(models.Manager):
    def get_by_natural_key(self, account, transaction_number):
        account_id = Account.objects.get_by_natural_key(*account).id
        return self.get(account=account_id, tx_number=transaction_number)
class TransactionDetailsManager(models.Manager):
    def combined(self):
        """Return a queryset of an ordered set of transaction including any splits"""
        # Force ordering so that parents precede children, and children are ordered by size
        qs_all = super().get_queryset().annotate(actual_transaction = Case(When(parent__isnull=True, then=F('id')),
                                                                    When(parent__isnull=False, then = F('parent'))),
                                              split_or_not = Case(When(parent__isnull=True, then=Value(0)), default=Value(1)),
                                              amount = Case(When(debit__isnull=False, then=F('debit')), default=F('credit')))

        return qs_all.order_by('transaction_date', 'actual_transaction', 'split_or_not', 'amount')
    def bank_only(self):
        """An ordered query set of just those transactions that would appear on a bank statement"""
        splits  = (Transaction.objects.filter(parent__id=OuterRef('id')).values('parent__id').
                           annotate(split_credit = Sum('credit', default=Decimal("0.00"))).
                           annotate(split_debit=Sum('debit', default=Decimal("0.00"))).values('split_debit','split_credit'))

        return (self.get_queryset().filter(parent__isnull=True).annotate(actual_transaction=F('id')).
                annotate(remaining_credit=F('credit') - Case(When(Exists(splits), then=Subquery(splits.values('split_credit')[:1])), default=Value(Decimal("0.00")) )).
                annotate(remaining_debit=F('debit') - Case(When(Exists(splits), then=Subquery(splits.values('split_debit')[:1])), default=Value(Decimal("0.00")) )).
                order_by('transaction_date','actual_transaction'))


class Transaction(models.Model):
    objects = TransactionManager()
    details = TransactionDetailsManager()
    tx_number = models.IntegerField(default=0)
    transaction_date = models.DateField()
    description = models.CharField(max_length=100)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    name = models.CharField(max_length=100, null=True, blank=True)
    category = models.CharField(max_length=100)
    debit = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    credit = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

Accounts/templates/FinancialYear.html
{% extends "accounts_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block PageStyles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Accounts/styles/financialyear.css' %}" xmlns="http://www.w3.org/1999/html">

{% endblock %}

{% block Title %}
    Brantham Garage Sale - Financial Years
{% endblock %}

{% block SnappableSections %}
    <h2>Financial years</h2>
     <div class="flex-table">
            <div class="flex-row">
            <span class="flex-cell header">Year</span>
            <span class="flex-cell header">Year Start</span>
            <span class="flex-cell header">Year End</span>
                <span class="flex-cell header"></span>
            </div>
            {% for year in FinancialYears %}
                <a href="{% url "Account:FinancialYearDetail" fy=year.year%}" >
                    <div  class="flex-row {% cycle 'odd' 'even' %} active_{{ year.active }}" >
                     <span class="flex-cell">{{ year.year }}</span>
                     <span class="flex-cell">
                         {{ year.year_start }}
                     </span>
                     <span class="flex-cell">
                         {{ year.year_end }}
                     </span>
                     <span class="flex-cell">
                         {% if year.active %}
                             Active
                         {% endif %}
                     </span>
                 </div>
                </a>
            {% endfor %}
     <div class="buttons">
         <input type="button" onclick='window.location = "{% url "Account:FinancialYearCreate" %}" ' value="Create New Record" >
     </div>

     </div>
{% endblock %}

Accounts/templates/FinancialYearCreate.html
{% extends "accounts_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block PageStyles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Accounts/styles/financialyear.css' %}" xmlns="http://www.w3.org/1999/html">

{% endblock %}
{% block Title %}
    Brantham Garage Sale - Financial Year {{ FinancialYear.year }}
{% endblock %}

{% block SnappableSections %}
    <H2>Creating Financial year {{ form.year.value }}</H2>
        <form method="POST">
            {% csrf_token %}
                <div class="fy_details">
                    {{ form }}
                    {%  if message %}
                        <div id="message">
                            {{ message }}
                        </div>
                    {% endif %}
            </div>
            <div class="buttons">
                <input type="button" value="Cancel" onclick='window.location="{%  url 'Account:FinancialYearList' %}" ' >
                <input type="reset" value="Reset Values">
                <input type="submit" value="Save">
             </div>
        </form>
{% endblock %}

Accounts/templates/FinancialYearEdit.html
{% extends "accounts_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block PageStyles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Accounts/styles/financialyear.css' %}" xmlns="http://www.w3.org/1999/html">

{% endblock %}
{% block Title %}
    Brantham Garage Sale - Financial Year {{ FinancialYear.year }}
{% endblock %}

{% block SnappableSections %}
    <H2>Edit details for Financial year {{ form.year.value }}</H2>
        <form method="POST">
            {% csrf_token %}
                <div class="fy_details">
                    {{ form }}
                    {%  if message %}
                        <div id="message">
                            {{ message }}
                        </div>
                    {% endif %}
            </div>
            <div class="buttons">
                <input type="button" value="Cancel" onclick='window.location="{%  url 'Account:FinancialYearDetail' fy=form.year.value %}" ' >
                <input type="reset" value="Reset Values">
                <input type="submit" value="Save">
             </div>
        </form>
{% endblock %}

Accounts/templates/FinancialYearView.html
{% extends "accounts_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block PageStyles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'Accounts/styles/financialyear.css' %}" xmlns="http://www.w3.org/1999/html">

{% endblock %}
{% block Title %}
    Brantham Garage Sale - Financial Year {{ FinancialYear.year }}
{% endblock %}

{% block SnappableSections %}
    <script lang="javascript">
    function cancel_close(){
        let dialog = document.getElementById('confirm_close_dialog');
        if (dialog.open)  dialog.close();
    }

    function confirm_close(){
        let dialog = document.getElementById('confirm_close_dialog');
        dialog.showModal();
    }
    </script>
<dialog id="confirm_close_dialog">
    <div>
    Please confirm that you wish to close this financial year ?
    </div>
    <div class="buttons">
    <input type="button" onclick="cancel_close()" value="No">
    <input type="button" onclick='window.location="{%  url "Account:FinancialYearClose" fy=FinancialYear.year %}" ' value="Yes - close this year">
    </div>
</dialog>

    <H2>Details for Financial year {{ FinancialYear.year }}</H2>
    <div class="fy_details">
        <div><span>Friendly Name: </span><span>{{ FinancialYear.year}}</span></div>
        <div><span>Year start: </span><span>{{ FinancialYear.year_start}}</span></div>
        <div><span>Year end: </span><span>{{ FinancialYear.year_end}}</span></div>
        <div><span>Active: </span><span>{{ FinancialYear.active|yesno:"Yes,No" }}</span></div>
    {%  if message %}
        <div id="message">
            {{ message }}
        </div>
    {% endif %}
    </div>

    <div class="buttons">
         <input type="button" onclick='window.location="{% url "Account:FinancialYearList" %}" ' value="Return to List">
         {%  if editable %}
         <input type="button" onclick='window.location = "{% url "Account:FinancialYearEdit"  fy=FinancialYear.year %}" ' value="Edit" >
         {%  endif %}
        {%  if FinancialYear.active %}
         <input type="button"  onclick="confirm_close()" value="Close this year">
        {%  endif %}
     </div>
{% endblock %}

Accounts/templates/accounts_base.html
{% extends "team_pages_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block PageStyles %}
    {{ block.super }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

<link rel="stylesheet" href="{% static 'team_pages/styles/team_page.css' %}" xmlns="http://www.w3.org/1999/html">
{% endblock %}

{% block Title %}
    Brantham Garage Sale - Team Page
{% endblock %}

{% block header %}
<div  class="breadcrumb">
    {% block breadcrumb %}
        {% breadcrumb %}
    {% endblock%}
</div>
{% endblock %}

{% block sidebar %}
        <div class="sidebar entry direct tooltip" item="{% url 'home' %}" xmlns="http://www.w3.org/1999/html">
            <a href="{% url 'home' %}">
                <img class="sidebar icon" alt="Home Page" id='id_home_page' src={% static "GarageSale/images/icons/menu/home-svgrepo-com.svg" %} >
                <label for="id_home_page">Home Page</label></a>
                <span class="tooltiptext right arrow">Return to Home Page</span>
        </div>
        <div class="sidebar entry direct tooltip" item="{% url 'TeamPages:Root' %}" xmlns="http://www.w3.org/1999/html">
            <a href="{% url 'TeamPages:Root' %}">
                <img class="sidebar icon" alt="Home Page" id='id_Teampages' src={% static "GarageSale/images/icons/menu/team-3-svgrepo-com.svg" %} >
                <label for="id_Teampages">Team Pages</label></a>
                <span class="tooltiptext right arrow">Team Pages</span>
        </div>
    {% if perms.Accounts.upload_transaction %}
        <div class="sidebar entry direct tooltip" item="{% url 'Account:upload_transactions' %}" xmlns="http://www.w3.org/1999/html">
        <a href="{% url 'Account:upload_transactions' %}">
            <img class="sidebar icon" alt="Upload Bank Transactions" id='id_upload' src={% static "GarageSale/images/icons/menu/upload-svgrepo-com.svg" %}>
            <label for="id_upload">Upload Transactions</label>
            <span class="tooltiptext arrow right">Upload Bank Transactions</span></a>
        </div>
        {% endif %}
    {% if perms.Accounts.view_transaction or perms.Account.edit_transaction %}
        <div class="sidebar entry direct tooltip" item="{% url 'Account:TransactionList' %}" xmlns="http://www.w3.org/1999/html">
        <a href="{% url 'Account:TransactionList' %}">
            <img class="sidebar icon" alt="Show/Edit Transactions" id='id_txlist' src={% static "GarageSale/images/icons/menu/list-svgrepo-com.svg" %}>
            <label for="id_txlist">Transactions</label>
            <span class="tooltiptext arrow right">Show/Edit Transactions</span></a>
        </div>
        {% endif %}
    {% if perms.Accounts.report_transaction %}
                <div class="sidebar entry direct tooltip" item="{% url 'Account:report' %}" xmlns="http://www.w3.org/1999/html">
        <a href="{% url 'Account:report' %}">
            <img class="sidebar icon" alt="Financial Reporting" id='id_reports' src={% static "GarageSale/images/icons/menu/report-svgrepo-com.svg" %}>
            <label for="id_reports">Financial Reports</label>
            <span class="tooltiptext arrow right">Financial Reports</span></a>
        </div>
    {% endif %}
    {% if perms.Accounts.Accounts.view_financialyear or perms.Accounts.change_financialyear %}
                <div class="sidebar entry direct tooltip" item="{% url 'Account:FinancialYearList' %}" xmlns="http://www.w3.org/1999/html">
        <a href="{% url 'Account:FinancialYearList' %}">
            <img class="sidebar icon" alt="Financial Year" id='id_fys' src={% static "GarageSale/images/icons/menu/monthly-calendar.svg" %}>
            <label for="id_fys">Financial Years</label>
            <span class="tooltiptext arrow right">Financial Years (View, Edit, Close)</span></a>
        </div>
    {% endif %}

{%  endblock %}

{% block SnappableSections %}

{% endblock %}

Accounts/templates/upload_transactions.html
{% extends "accounts_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}

{% block Title %}
    Brantham Garage Sale - Upload Transactions
{% endblock %}

{% block SnappableSections %}
<h1>Upload Transactions</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
{% endblock %}