GarageSale/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from .views import general_views

from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", general_views.home, name="home"),
    path("newhome", TemplateView.as_view(template_name='home.html'), name="NewHome"),
    path("getInvolved", RedirectView.as_view(url=reverse_lazy('Location:view'))),
#    path("getInvolved", include('Location.urls'), name="getInvolved"),
    path('about_us', TemplateView.as_view(template_name='aboutUs.html'), name='AboutUs'),
    path('contact', TemplateView.as_view(template_name='contact.html'), name='ContactUs'),
    path('privacy', TemplateView.as_view(template_name='privacy_policy.html'), name='Privacy'),
    path('blind_auction', TemplateView.as_view(template_name='blind_auction.html'), name='BlindAuction'),
    path('donate', TemplateView.as_view(template_name='donate.html'), name='Donate'),
    path('location/', include('Location.urls')),
    path('team_page/', include('team_pages.urls', 'TeamPages')),
    path('news/', include('News.urls')),
    path('user/', include('user_management.urls')),
#    path('billboard/', include('Billboard.urls')),
#    path('sale_location/', include('SaleLocation.urls')),

    # path('test/<int:case>/', views.testing, name='test'),
    path('sponsors/', include('Sponsors.urls')),
    path('CraftMarket/', include('CraftMarket.urls')),
    path('Account/', include('Accounts.urls')),

    path('mapping/', include('DjangoGoogleMap.urls')),
    path('summernote/', include('django_summernote.urls')),

    path("GoogleDrive/", include('GoogleDrive.urls', namespace='GoogleDrive') ),

]


if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

News/urls.py
#!/usr/bin/env python
# coding=utf-8
"""
    GarageSale.urls.py : 

Summary :
    
    
Use Case :
    
    
Testable Statements :
    ...0
"""
from .views import Article, news_page,news_letter_subscribe

from django.urls import path

app_name = "News"

urlpatterns = [
    path("", news_page, name="NewsPage"),
    path("article/<slug:slug>", Article.as_view(), name="article"),
    path("subscribe", news_letter_subscribe, name='subscribe'),
]

Sponsors/urls.py
#!/usr/bin/env python
# coding=utf-8
"""
    GarageSale.urls.py : 

Summary :
    
    
Use Case :
    
    
Testable Statements :
    ...
"""
from django.urls import path
from .views import sponsor_list

app_name = "sponsors"
urlpatterns = [
    path("", sponsor_list, name="sponsor_list"),
]

team_pages/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from GarageSale.views.template_views import TemplatesView
from . import views
from . import stats_view

app_name = 'TeamPages'
urlpatterns = [
    path('', views.TeamPage.as_view(), name='Root'),
    path('<int:event_id>/', views.TeamPage.as_view(), name='EventRoot'),
    path('<int:event_id>/stats/', stats_view.event_stats, name='EventStats'),

    # TODO Rework without Generic Views = more trouble than they are worth
    path('motd/create/', views.MotDCreate.as_view(), {'action': '_create'}, name='MotdCreate', ),
    path('motd/<int:motd_id>/edit/', views.MotDEdit.as_view(), name='MotdEdit'),
    path('motd/<int:motd_id>/view/', views.MotDView.as_view(), name='MotdView'),
    path('motd/<int:motd_id>/delete/', views.delete_motd, name='MotdDelete'),

    path('news/', views.NewsRoot.as_view(), name='News'),
    path('news/create/', views.NewsCreate.as_view(), name='CreateNews'),
    path('news/<int:news_id>/edit/', views.NewsEdit.as_view(), name='EditNews'),
    path('news/<int:news_id>/view/', views.NewsView.as_view(), name='ViewNews'),
    path('news/<int:news_id>/publish/', views.PublishNews, name='PublishNews'),
    path('news/<int:news_id>/delete/', views.NewsDelete.as_view(), name='DeleteNews'),

    path('event/', views.TeamPage.as_view(), name='Event'),
    path('event/<int:event_id>/', views.TeamPage.as_view(), name='EventDisplay'),

    path('event/create/', views.EventCreate.as_view(), name='EventCreate'),
    path('event/<int:event_id>/edit/', views.EventEdit.as_view(), name='EventEdit'),
    path('event/<int:event_id>/view/', views.EventView.as_view(), name='EventView'),
    path('event/<int:event_id>/use/', views.event_use, name='EventUse'),
    path('event/<int:event_id>/ad_board/',views.ad_board_csv, name='EventAdBoard'),

    path('sponsor/<int:event_id>/', views.SponsorsRoot.as_view(), name='Sponsor'),
    path('sponsor/<int:event_id>/create/', views.SponsorCreate.as_view(), name='SponsorCreate'),
    path('sponsor/<int:sponsor_id>/view/', views.SponsorView.as_view(), name='SponsorView'),
    path('sponsor/<int:sponsor_id>/edit/', views.SponsorEdit.as_view(), name='SponsorEdit'),
    path('sponsor/<int:sponsor_id>/confirm/', views.SponsorConfirm.as_view(), name='SponsorConfirm'),
    path('sponsor/<int:sponsor_id>/delete/', views.SponsorDelete.as_view(), name='SponsorConfirm'),
    path("GoogleDrive/", TemplateView.as_view(template_name='GoogleDrive.html'), name='GoogleDrive'),
]

Sponsors/models.py
from django.db import models
from GarageSale.models import EventData
from django.conf import settings
# Create your models here.

from django.utils.text import slugify


def save_logo_to( instance, file_name:str):
    return f'sponsors_{instance.event.event_date.year}/{slugify(instance.company_name)}_{file_name}'


class Sponsor(models.Model):
    class Meta:
        permissions = [ ("confirm_sponsor", "Can confirm a Sponsor")
        ]
    event = models.ForeignKey( EventData, related_name='sponsors', on_delete=models.CASCADE, null=True)
    company_name = models.CharField(max_length=120)
    logo = models.ImageField( upload_to=save_logo_to, blank=True)
    description = models.TextField(max_length=1000)
    gift = models.TextField(max_length=1000, null=True, blank=True)
    lead_provider = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)
    twitter = models.URLField(blank=True)
    instagram = models.URLField(blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=12)
    creation_date = models.DateTimeField(auto_now_add=True)
    confirmed = models.BooleanField(default=False)

Sponsors/views.py
from django.shortcuts import render

# Create your views here.

from django.template.response import TemplateResponse
from .models import Sponsor


def social_media_items():
    return ['website','facebook','instagram']


def sponsor_list(request):
    sponsors = Sponsor.objects.filter(event__id = request.current_event.id)
    return TemplateResponse(request,'view_sponsors.html',
                            context={'sponsors': sponsors,
                                     'socials':social_media_items() } )

team_pages/views.py
import datetime
import csv
import logging

from django.forms import fields
from django.core import exceptions
from django.core.exceptions import BadRequest
from django.db.models import Q
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.template.response import TemplateResponse
from django.views import View
from django.http import HttpResponseServerError, HttpResponse
from django.contrib.admin.widgets import AdminDateWidget

from News.models import NewsArticle
from News.views import publish_news
from Sponsors.models import Sponsor
from GarageSale.models import MOTD, EventData
from .forms import NewsForm, MotdForm, EventForm, SponsorForm
from Sponsors.views import social_media_items
from abc import abstractmethod
from Location.models import Location
import logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

def PublishNews(request, news_id):
    publish_news(request, news_id)
    fragments = [key for key, item in request.GET.items() if item == '']
    return redirect(reverse('TeamPages:News') + (('?' + '&'.join(fragments)) if fragments else ''))

def custom_news_query_set(param_dict):
    unpublished = 'unpublished' in param_dict
    xpublished = 'Xpublished' in param_dict
    xfront_page = 'XFrontPage' in param_dict
    xnot_front_page = 'XNotFrontPage' in param_dict
    expired = 'expired' in param_dict

    # base includes Everything
    if unpublished:
        qp = Q(published=False)
    else:
        qp = Q(published=True)

    if not xpublished:
        qp |= Q(published=True)
    else:
        qp |= Q(published=False)

    if xfront_page:
        qf = Q(front_page=False)
    else:
        qf = Q(front_page=True)

    if xnot_front_page:
        qf |= Q(front_page=True)
    else:
        qf |= Q(front_page=False)

    if not expired:
        q = (qp & qf) & Q(expire_by__isnull=True) | Q(expire_by__gte=datetime.date.today())
    else:
        q = qp & qf

    return NewsArticle.chainable.filter(q).order_by('-published', 'publish_by', '-front_page')


class CombinedView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """
    An All purpose class for displaying a list and detail/creation forms in one template

    Attributes :
        login_url & redirect_field_name - required by the LoginRequiredMixin
        permission_required - as required by the PermissionRequiredMixin
        template_name : the template to be invoked by the instance to display the data and forms
        form_class : the detail forms to be used - can be none if the detail doesn't need a forms (eg a confirmation button)
        model_class : must be a class of a model which can be instantiated
        success_url :  a static URL to be used if the POST operation succeeds

    Methods :
        get_form( form_instance ) -> Form :
                Can be used to modify the forms if necessary (for example change widgets)

        get_success_url( request, context, **kwargs ) -> url
               If implement this defines the url to be used when the POST succeeds - used in presence to self.success_url

        get_list_query_set( request, **kwargs) -> queryset
               Returns the query set for the sub-list

        get_context_data(request, **kwargs) -> dict
                Must be overridden - returns the context used to drive the relevant template.

        get_object( request, **kwargs) - Model instance
                Must be overridden - will return the instance to be used on the forms (for edit/views)
                Can return None (ie. for create and non-forms actions)

        get_new_instance( request, forms, **kwargs):
                Can be implemented - used when self.get_object returns None
                Can also return None to prevent a save.

        self.do_post_success( self, request, context=None, model_instance=None, form_instance=None, **kwargs)
            can be implemented - can be used for any reason during the POST processing.
            Called once the forms is known to be valid.
            If it returns False then the automatic updating of the instance from the form_data
            if this method updates the instance and intends to return False it must also save the instance
            returning False does not constitute a failure.

            Might need a Pre and post save method in future.
    """
    login_url = '/user/login'
    redirect_field_name = 'redirect'
    permission_required = None
    template_name = ''
    form_class = None
    model_class = None
    success_url = ''

    def post_save(self, request, instance, form, **kwargs):
        return None

    def get_form(self, form_instance=None):
        return form_instance

    def get_success_url(self, request, context, **kwargs):
        """Returns the URL to be used when the POST succeeds"""
        return NotImplemented

    def get_list_query_set(self, request, **kwargs):
        """Returns a filtered and ordered queryset for the sub-list"""
        return NotImplemented

    @abstractmethod
    def get_context_data(self, request, **kwargs):
        """Must be overridden to provide extra context data for the templates"""
        return {}

    @abstractmethod
    def get_object(self, request, **kwargs):
        """Must be overridden to provide the actual model instance used on this forms"""
        return NotImplemented

    def do_post_success(self, request, context=None, model_instance=None, form_instance=None, **kwargs):
        """Can be overridden to provide an alternative to saving an instance
           If the method returns False then the instance isn't saved.
        """
        return True

    def __init__(self, *args, **kwargs):
        """Validate that some forms of success_url is provided"""
        super().__init__(*args, **kwargs)
        if not hasattr(self, 'success_url') and not hasattr(self, 'get_success_url'):
            raise exceptions.ImproperlyConfigured('Either "success_url" attribute or "get_success_url" '
                                                  'method needs to be implemented') from None

    def get(self, request, **kwargs):
        """Initial get request"""
        context = self.get_context_data(request, **kwargs)
        instance = self.get_object(request, **kwargs)

        if self.form_class:
            if instance:
                context['form'] = self.get_form(self.form_class(instance=instance))
            else:
                context['form'] = self.get_form(self.form_class())
        else:
            context['form'] = None

        return TemplateResponse(request, self.template_name, context=context)

    def post(self, request, **kwargs):
        form_data = request.POST

        context = self.get_context_data(request, **kwargs)
        instance = self.get_object(request, **kwargs)

        if self.form_class:
            the_form = self.get_form(self.form_class(request.POST, request.FILES))
        else:
            the_form = None

        # If there is a forms instance then validate the forms (and return if errors)
        if the_form:
            if not the_form.is_valid():
                context['form'] = the_form
                return TemplateResponse(request, self.template_name, context=context)

        # Check for the do_post_success method (if it exists)
        if hasattr(self, 'do_post_success'):
            post_success = self.do_post_success(request, context=context, model_instance=instance, form_instance=the_form, **kwargs)
        else:
            post_success = True

        # A value of post_success of False suppress the automated updating the instance and saving.

        # If the post success was affirmative then update the instance from the forms
        if post_success:
            if instance and the_form:
                for field_name in the_form.fields:
                    logger.info(f'Updating {field_name} from form data')
                    image_field= isinstance(the_form.fields[field_name], fields.ImageField)
                    if image_field:
                        if f'{field_name}-clear' in request.POST:
                            setattr(instance, field_name, '')
                        elif field_name in request.FILES:
                            setattr(instance, field_name, the_form.cleaned_data[field_name])
                    else:
                        setattr(instance, field_name, the_form.cleaned_data[field_name])
            elif not instance and the_form:
                if hasattr(self, 'get_new_instance'):
                    instance = self.get_new_instance(request, the_form, **kwargs)
                elif self.model_class:
                    instance = self.model_class(**the_form.cleaned_data)
                else:
                    instance = None

            if instance:
                instance.save()
                self.post_save(request, instance, the_form, **kwargs)

        # Redirect to the correct success url
        if hasattr(self, 'get_success_url'):
            url = self.get_success_url(request, context, **kwargs)
            if url is not NotImplemented:
                return redirect(url)

        if hasattr(self, 'success_url') and self.success_url:
            return redirect(self.success_url)
        else:
            return HttpResponseServerError('No defined success_url for this request !')


class NewsRoot(CombinedView):
    permission_required = ["News.can_manage_news"]
    template_name = 'news/tp_manage_news.html'
    form_class = NewsForm
    model_class = NewsArticle

    def get_success_url(self, request, context=None, **kwargs):
        fragments = [key for key, item in self.request.GET.items() if item == '']
        return reverse('TeamPages:News') + ('?' + '&'.join(fragments)) if fragments else ''

    def get_object(self, request, **kwargs):
        return None

    def get_list_query_set(self, request, **kwargs):

team_pages/templates/sponsors/tp_confirm_sponsor.html
{% extends "sponsors/tp_event_sponsor.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}
{% load sponsor_tags %}

{% block detail %}
<div class="detail bordered">

    <h3>Confirming sponsorship lead from '{{company_name}}'</h3>
    <form method="POST">
        {% csrf_token %}
        <div class="buttons">
            <input id='tp_cancel_form' item_id="{{form.instance.event_id}}" type="button" value="Cancel">
            <input id="tp_save_form"  type="submit" value="Confirm this sponsorship lead">
        </div>
    </form>
</div>
</div>
{% endblock %}

team_pages/templates/sponsors/tp_create_sponsor.html
{% extends "sponsors/tp_edit_sponsor.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}
{% load sponsor_tags %}


    {% block buttons %}
            <input id='tp_cancel_form' item_id="{{form.instance.event_id}}" type="button" value="Cancel">
            <input id="tp_save_form"  type="submit" value="Save this new entry">
    {% endblock %}

team_pages/templates/sponsors/tp_delete_sponsor.html
{% extends "sponsors/tp_event_sponsor.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}
{% load sponsor_tags %}

{% block detail %}
<div class="detail bordered">

    <h3>Deleting sponsorship lead from '{{company_name}}'</h3>
    <form method="POST">
        {% csrf_token %}
        <div class="buttons">
            <input id='tp_cancel_form' item_id="{{form.instance.event_id}}" type="button" value="Cancel">
            <input id="tp_save_form"  type="submit" value="Confirm Deletion of this sponsorship lead">
        </div>
    </form>
</div>
{% endblock %}

team_pages/templates/sponsors/tp_edit_sponsor.html
{% extends "sponsors/tp_event_sponsor.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}
{% load sponsor_tags %}

{%  block PageStyles %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'Sponsors/styles/sponsor_style.css' %}">
{% endblock %}

{% block detail %}
<div class="detail bordered">
    <script>
        function preview_image(event) {
            var reader = new FileReader();
            reader.onload = function(){
              var output = document.getElementById('output_image');
              var span = document.getElementById('id_preview');
              span.style.display='inline-block';
              output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
    <form method="POST" enctype='multipart/form-data'>
        {% if form.instance.confirmed == False %}
        <div class="warning">
            Not Confirmed
        </div>
        {% endif %}
        {% csrf_token %}
        <div>
            {{ form.non_field_errors }}
        </div>
        <div id="tp_sponsor_core">
            <div class="name">
                <div class="errorlist">
                    {{ form.company_name.errors }}
                </div>
                <label for="id_company_name">Company Name</label>{{form.company_name}}
            </div>
            <div class="lead_provider">
                <b>{{ form.lead_provider.label }}</b>
                    {%  if action == "create" %}
                            {{ request.user.full_name }}
                    {% elif form.lead_provider %}
                            {{  form.instance.lead_provider.full_name }}
                    {%  else %}
                            Unknown User
                    {% endif %}
            </div>
        <hr>
                <div class="image edit">

                    {% if form.instance.logo != ''%}
                        <span><label for="tp_current_logo">Current Logo</label><img id='id_current_logo' alt="{{form.company_name.logo}}"src="{{MEDIA_URL}}{{form.instance.logo}}" /></span>
                    {% endif %}

                    <div class="edit-logo">
                        <span class="clear-logo">
                        <label for="id_logo_clear">Clear</label>
                        <input type="checkbox" name="logo-clear" id="id_logo_clear">
                        </span>
                        <span class="change-logo">
                        <label for="id_logo">Change</label>
                        <input type="file" onchange="preview_image(event)" name="logo" accept="image/*" id="id_logo">
                        <span id="id_preview" style="display:none;">Preview : <img id="output_image" height=50px width=50px\></span>
                        </span>
                    </div>
                </div>
        <hr>
                <table class="inner">
                    <tr class="description">
                        <div class="errorlist">
                            {{ form.description.errors }}
                        </div>

                        <th><label for="id_description">Description</label></th>
                        <td>{{form.description | safe}}</td>
                    </tr>
                    <tr class="gift">
                        <div class="errorlist">
                            {{ form.gift.errors }}
                        </div>
                        <th><label for="id_gift">Gift</label></th>
                        <td>{{form.gift | safe }}</td>
                    </tr>
                    </table>
                <hr>
            <div class="contact">
                <div class="phone" >
                        <img alt='Phone' src="{% static 'GarageSale/images/icons/phone-calling-svgrepo-com.svg' %}" />
                    <b>Phone</b> : {{form.phone}}
                </div>
                <div class="email" >
                        <img alt='Email' src="{% static 'GarageSale/images/icons/email-open-svgrepo-com.svg' %}" />
                    <b>email</b> : {{form.email}}
                </div>
                <div class="icons">
                    {% for social in socials %}
                        <div class="social">
                            <span id="id_social_label" class="social_entry"><label id="id_{{ social }}_link">{{social}}</label></span>
                            <span id="id_social_icon" class="social_entry">{% get_social_icon social %}</span>
                            <span id="id_social_link" class="social_entry">{% get_form_field form social %}</span>
                        </div>
                    {% endfor %}
                </div>
            </div>
        <hr>
            <div class="buttons">
            {% block buttons %}
                <input id='tp_cancel_form' item_id="{{form.instance.event_id}}" type="button" value="Cancel">
                <input type="reset" value="Reset to defaults">
                <input id="tp_save_form"  type="submit" value="Save this entry">
            {% endblock %}
            </div>
        </div>
    </form>
</div>
{% endblock %}

team_pages/templates/sponsors/tp_event_sponsor.html
{% extends "team_pages_base.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}
{% load sponsor_tags %}

{% block PageScripts %}
    {{ block.super }}
<script type="text/javascript" src="{% static 'team_pages/js/news_page.js' %}"></script>
    {%  endblock %}



{% block SnappableSections %}
    <div class="snappable-section">
<script>
    const patterns = new Map([
    {% for path in patterns %}
        {% if forloop.last %}
           ['{{path.action}}', '{{path.regex | safe}}'] ]
        {% else %}
           ['{{path.action}}', '{{path.regex | safe }}'],
        {% endif %}
    {% endfor %}
    );
</script>
<input type="hidden" value="{{event_id}}" id="tp_event_id">
<div id="id_article_list" class="sublist bordered">
    <div id="id_al_toolbar" class="actions">
        <ul>
            {% if perms.Sponsors.can_create_sponsor %}
        <li><span id="tp-create" action="create">&#127381;</span></li>  <!-- New Icon -->
            {% endif %}
        </ul>
    </div>
    <table class="data_list" id="id_entry_list">
        <tr class="heading">
            <th class="heading name">
                Company Name
            </th>
            <th class="heading confirmed">
                Confirmed?
            </th>
            <th class="heading action"> </th>
        </tr>
        <tbody id="tp_tbody_item_list">
        {% for item in sub_list_data %}
            <tr class="data-row {% cycle 'odd' 'even' %}">
                <td class="name">
                    {{ item.company_name }}
                </td>
                <td>
                        {% if item.confirmed %} &#x2705;{%else%}&#x274E{% endif %}
                </td>
                <td class="icons">
                    <span tp_row_id="{{item.id}}" tp_action="view">&#x1F50D;</span>
                    {% if perms.Sponsors.change_sponsor %}
                        <span tp_row_id="{{item.id}}" tp_action="edit">&#x270E;</span>
                    {% endif %}
                    {% if perms.Sponsors.can_confirm_sponsor and not item.confirmed %}
                        <span tp_row_id="{{item.id}}" tp_action="confirm">&#128077;</span>
                    {% endif %}
                    {% if perms.Sponsors.delete_sponsor and not item.confirmed %}
                        <span tp_row_id="{{item.id}}" tp_action="delete">&#128465;</span>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
    {% block detail %}
    {% endblock %}
    </div>
{% endblock %}

team_pages/templates/sponsors/tp_view_sponsor.html
{% extends "sponsors/tp_event_sponsor.html" %}
{% load static %}
{% load user_management_tags %}
{% load team_page_tags %}
{% load sponsor_tags %}

{% block PageStyles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'Sponsors/styles/sponsor_style.css' %}">
{% endblock %}

{% block detail %}
    <div class="detail bordered">
        {% if form.instance.confirmed == False %}
        <div class="warning">
            Not Confirmed
        </div>
        {% endif %}
        <div id="tp_lead_provider">
            <div id="tp_lead_name">
            {% if form.lead_provider %}
                <label>Lead Provided by</label>: {{ form.instance.lead_provider.full_name }}
            {% endif %}
            </div>
        </div>
        <div id="tp_sponsor_core">
            <div class="name">
                <h3>{{form.instance.company_name}}</h3>
            </div>
            <div class="inner">
                {% if form.instance.logo != '' %}
                    <div class="image">
                        <img src="{{ MEDIA_URL }}{{form.instance.logo}}" class="logo">
                    </div>
                {% endif %}
                <div class="description">
                    {{form.instance.description | safe}}
                </div>
            </div>
        </div>
        <div class="contact">
            <div style="float:left;">
                <div class="phone" >
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
                    </svg>
                    <b>Phone</b> : {{form.instance.phone}}
                </div>
                <div class="email" >
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                    <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1zm13 2.383-4.708 2.825L15 11.105zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741M1 11.105l4.708-2.897L1 5.383z"/>
                    </svg>
                    <b>email</b> : <a href="mailto:{{form.instance.email}}">{{form.instance.email}}</a>
                </div>
            </div>
            <div class="icons">
                {% for social in socials %}
                    {% social_media_link form.instance social %}
                {% endfor %}
            </div>
        </div>
        <div class="buttons">
            <input id='tp_cancel_form' item_id="{{form.instance.event_id}}" type="button" value="Cancel">
            <input id="tp_edit_form" item_id="{{form.instance.id}}" type="button" value="Edit this entry">
        </div>
    </div>
{% endblock %}